### ISSUE TITLE
Ignore words that include hyphen

### ISSUE THREAD

**Issue by itlackey** [Microsoft/vscode-spell-check#10]
It appears that adding words that include a hyphen to the ignore list does not work. For example, I added "grunt-cli" to my spell.json file and it still appears in the error list.

**Comment by seanmcbreen** [comment]
First off sorry for the slow reply - I've been on sabbatical (still am :)).

Unfortunately my code (and the underlying service) are really aggressive in ignoring several chars... 

https://github.com/Microsoft/vscode-spell-check/blob/master/extension.ts#L60
```
`"!#$%&()*+,.\/:;<=>?@[]\^_{|}
```

Any word with those as a separator will not work will with my dictionary logic :( 

To make it worse I don't have a good work around.

If you come up with a brilliant idea please LMK but for now I think I should close this issue.   Sorry.  Thank you for using VS Code and this extension!

Sean
