### ISSUE TITLE
Ignore code

### ISSUE THREAD

**Issue by variab1e** [Microsoft/vscode-spell-check#11]
First off - thanks heaps for the work, really helps me out, as I've been using vscode for markdown editing a lot lately. 

I was hoping you could either make it default or add an option to:
1. Disable grammar / spell checking of URLs (ie the URL part between `[]` in `()[]`), and
2. Disable grammar / spell checking of anything in the code quotes or whatever they are called (ASCII char #96, aka hex x60)
3. Code blocks:
  * in ```
  * indented

Also, I'd probably specify in the README that the config currently needs to go in the current project's/workspace's `.vscode` directory, as simply saying `.vscode` directory had me trying to put it in the `$HOMEDIR\.vscode` directory to no avail, it took a search through the code and a look at the other issue #7 to realize my error, not a huge deal, but it might help others.

**Comment by seanmcbreen** [comment]
I plan to add in the ability to define a set of reg-exp that will be used to ignore a section of the document for checking - the project started with this including the ones you mention.  I will make it optional via the config file as it can impact other languages people use.

This probably will happen in the next week or so assuming I get the time (on holiday right now :)).

Thanks for posting this and sorry for the long delay.
Sean

**Comment by variab1e** [comment]
No worries. Thanks!

**Comment by seanmcbreen** [comment]
Hi,

I added in a new setting for this in 0.5.0 which I just published.  You just need to craft RegExps to match what you are after.  A good tool to help is https://regex101.com/ just don;t forget to escape out the chars once added to the JSON file.

Some examples.  The top 5 do a variety of links and the last one does code blocks.

Hope that's what you are after I'll close this for now and LMK if you have any issues.

Sean

```
    "ignoreRegExp": [
        "/(http\\\\S*)/gm",
        "/\\\\(.*.png\\\\)/g",
        "/\\\\(.*.gif\\\\)/g",
        "/\\\\(.*.md\\\\)/g",
        "/\\\\(.*.jpg\\\\)/g",
        "/^((`{3}\\\\s*)(\\\\w+)?(\\\\s*([\\\\w\\\\W]+?)\\\\n*)\\\\2)\\\\n*(?:[^\\\\S\\\\w\\\\s]|$)/gm"
    ]
```
