### ISSUE TITLE
Maintain casing after replacement

### ISSUE THREAD

**Issue by AndrewGaspar** [Microsoft/vscode-spell-check#12]
When you correct a word that is capitalized (because it is, say, at the beginning of a sentence), the word it is replaced with is lower case.

**Comment by seanmcbreen** [comment]
That's a great suggestion I'll add that to the backlog - I'm on leave right now but I think that would be easy enough to do.  Other similar ideas that I've liked is to add to dictionary all versions of a word e.g. certain and Certain.

Sorry for the long delay, it may also be a while for this one but I will do it.
Sean

**Comment by frodefi** [comment]
+1

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
