### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by adolfobarreto75** [Microsoft/vscode-spell-check#13]
Hi,

I installed this today and it's not working. I checked through the files in the .vscode file and everything seems to be in-place. I'm i skipping a step or do I have something else to activate? Thanks-Adolfo

**Comment by gregvanl** [comment]
Hi Adoflo,
Is the spell check extension still not working for you?  There shouldn't be any extra steps besides restarting VS Code.  You don't see any spelling checks when you open a Markdown file?
- Greg

**Comment by adolfobarreto75** [comment]
Hi Greg,
Thanks for the response. No, I get no errors or spellcheck. It shows up under installed extensions and I'm not getting any errors.
Thanks - Adolfo

**Comment by seanmcbreen** [comment]
Hi,

Sorry you are having issues, one question that may help narrow this down is what language are you using (default support is markdown/text only).  You can change the supported languages but those are the ones we start with.

Other than that I'm a little stumped so may need a little more detail on a file that is not working (a screenshot of the file content).

Definitely want to help so let me know.
Sean

p.s. I'm on holiday at the moment but will work to be pretty responsive.

**Comment by adolfobarreto75** [comment]
@seanmcbreen Please enjoy your holiday! We can go over it when your back. Let me know...Thanks - Adolfo

**Comment by saj1th** [comment]
It says "LanguageID: plaintext not suported for spell checking." for me.

**Comment by saj1th** [comment]
fixed by adding https://github.com/Microsoft/vscode-spell-check/blob/master/.vscode/spell.json to the .vscode dir

**Comment by seanmcbreen** [comment]
Hopefully this is all resolved now so good luck.  Re-open if not.
