### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by thomaswp** [Microsoft/vscode-spell-check#14]
I'm trying to get spellcheck for .html files. I've created a spell.json file in .vscode folder (under my user folder in Windows). I've added "html" to the list of "languageIDs", restarted Code and reloaded the window, to no avail. I don't think config is working.

**Comment by seanmcbreen** [comment]
Hi,

Sorry for the delay here - I've been out of the office for a while (I actually still am :)).  But I think I can help here :)

The config file should live under your specific project vs. globally on disk.  So in my case for this specific project the physical path is...

```
C:\src\vscode-spell-check\.vscode\spell.json
```

It's the same location we use for work-space settings.  I think that should sort you out - there has been a suggestion #7 for a global setting file and I plan to add that in as well.

Sorry for the confusion and delay here I hope you enjoy VS Code!

Sean
