### ISSUE TITLE
Spell checking is not working behind proxy

### ISSUE THREAD

**Issue by zminic** [Microsoft/vscode-spell-check#16]
Although vscode works behind proxy normally spell checker is unable to display corrections when behind proxy.

**Comment by seanmcbreen** [comment]
This unfortunately is true - I've added an enhancement label for this but for now have no immediate plans to fix this sorry :cry: 

Sean

**Comment by markusmauch** [comment]
I'd really love to see this, too... At the moment the extension is useless for us.

**Comment by aaroncalderon** [comment]
@zminic Hi, what are your symthoms? 
- Do you get the words underlined as spelling errors but cannot get the correction suggestions? or
- Do you not get anything at all?

I as, becaue i just updated to vscode 1.3 shortly after installing the extension, and I do not recall if the extension had worked before or not. Then, I am also behind a proxy, so I'm not sure if I am experiencing your issue or the extension does not work with the new version of vscode.

Thanks.

**Comment by zminic** [comment]
@aaroncalderon Hi,

When behind proxy I didn't get anything at all.

I tried again with newest versions and problem seems to remain.

**Comment by seanmcbreen** [comment]
Hi unfortunately the checker does not today support proxys it calls the service directly.  There is a local spell checker available (has a few less features) otherwise I'm open to a pull request :)

**Comment by zminic** [comment]
Hi, I have checked out how this could be implemented and came to conclusion that teacher npm package uses "request" library to perform requests. It seems that they use outdated version (or a fork), and in current version "request" library allows to specify proxy via environment variables. If they update request library then this issue will be fixed, probably readme will need to be updated.

I have opened an issue in teacher repository.

**Comment by awellock** [comment]
Thanks for tracking that down @zminic! I am hoping that this get fixed quickly this is a super useful extension when it works.

**Comment by awellock** [comment]
Wanted to make everyone aware of the good work @zminic is doing for those of us that can not spell. [enable proxy](https://github.com/vesln/teacher/pull/7). Thanks again!

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
