### ISSUE TITLE
spell check code

### ISSUE THREAD

**Issue by janmarek** [Microsoft/vscode-spell-check#17]
Hi,
I like what they have in IDEA based IDEs. They can universally spell check symbols in code.

Because you know that you can parse

* SomeClassName as words some class name
* SOME_CONSTANT as words some constants
* underscored_symbol_name as words underscored symbol names
* etc

and then you can check it against vocabulary.

With this approach you can support all programming languages without any extra work for each of them.

**Comment by Wayofthesin** [comment]
It's much more complicated. What about shortcuts? Abbreviations? Kewyords? Name of libraries?
  - First of all to spellcheck in code it shouldn't mark spelling mistake as an error (use different underline color).
  - It would need to extend dictionary (on system and on workspace scope separately)
  - It needs some prebuild vocabulary for language keywords (note that u may change language).

That's a lot complicated. Probable exceeds this project (which is text spellchecker).

**Comment by seanmcbreen** [comment]
Yes for now the spell checker does not have any semantic understanding of the language.  It's definitely possible to do but it is beyond the planned scope of the extension for now.  As a result the 'hack' is to add additional check types to the `spell.json` file e.g. `python` and add regexps to help scope what to check - see issue #28
