### ISSUE TITLE
Suggestions missing on ALT+. but present for F8

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode-spell-check#19]
Suggestions missing on ALT+. but present for F8

Latest patched Windows 10, brand new install of latest VSCode.

Language: default English.

Word: "acceptence"

Please let me know if I can provide more details.

**Comment by seanmcbreen** [comment]
I'm able to repro that - I'll need to look into the issue and come back to see what is required to fix it :)  Thanks for reporting it.

**Comment by leegee** [comment]
I took a look in the 'config' JSON file, and found that one word had been added thrice -- not sure if it is connected.

**Comment by seanmcbreen** [comment]
I had another crack at this and could no longer repro the issue.  Are you still seeing this problem/do you have any repeatable steps?

Sorry,
Sean

**Comment by leegee** [comment]
Ditto. Perhaps VSCode updates have cured it? I have spotted another issue, though, for another ticket.
