### ISSUE TITLE
New language support

### ISSUE THREAD

**Issue by Nioufe** [Microsoft/vscode-spell-check#2]
I saw that the plugin is based on https://www.npmjs.com/package/teacher, which supports other languages than english.

Would you consider pull request adding an option, or a way to detect the language used in markdown files?

Thanks for the nice extension, have a good day!

**Comment by seanmcbreen** [comment]
Absolutely that would be great - I imagine the easiest way [for the user] would be a new setting added to the `spell.json` file for the default language to use.  

The code can then continue to [default to English](https://github.com/Microsoft/vscode-spell-check/blob/master/extension.ts#L129) (if the file is not there) allowing it to continue to work immediately upon install.

Great idea.

**Comment by seanmcbreen** [comment]
Ha - I just saw that @alefragnani is already on the case and I just merged his pull request a little testing and the I'll re-publish.  Also need to update the read-me.

**Comment by seanmcbreen** [comment]
Published an update the readme is a little rough but it's now out there.

**Comment by Nioufe** [comment]
Damn that was fast.

Thanks a lot!

**Comment by alefragnani** [comment]
@Nioufe @seanmcbreen glad I could help :smile: 
I was thinking to contribute more, maybe the _lightbulb_ idea. Is there any priority in mind?
