### ISSUE TITLE
JavaScript not supported

### ISSUE THREAD

**Issue by jreadytalk** [Microsoft/vscode-spell-check#20]
Please support spell checking JavaScript.

![screen shot 2016-03-16 at 12 39 05 pm](https://cloud.githubusercontent.com/assets/8117740/13824562/26773586-eb74-11e5-80fb-aebdc9e06b86.png)

**Comment by seanmcbreen** [comment]
:)

One thing you can do is add 'javascript' to the language ID field in the `spell.json` file.  That will activate spell checking for the file.

It will be pretty ugly however as keywords etc will all be picked up.

**Comment by sarbbottam** [comment]
Can we not **spell check only the comments** in javascript or any language?

**Comment by seanmcbreen** [comment]
The easy way to do that would be to create a regexp to ignore all items except comments in JavaScript.  The `spell.json` file supports an array of regexps for text to ignore - in this case all text except comments.

For now the extension lacks semantic understanding of the document so this is the best path.  

Some suggestions wee made in this issue #28
