### ISSUE TITLE
FEATURE: context-menu suggestions, add, ignore

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode-spell-check#21]
Not sure if you get access to the context menu, but it would be nice, and familiar.

**Comment by seanmcbreen** [comment]
Unfortunately that's not a supported extension point for VS Code today.

**Comment by leegee** [comment]
Can't we leave the ticket open as a show of demand for the VSCode team, to encourage them to add this feature?

**Comment by seanmcbreen** [comment]
We can - however they hear you loud and clear - I'm a core team member for VS Code :smile:

Adding additional UX customization is something we have strayed away from to date.  But it's also something we are always discussing.  The thing we have wanted to avoid is overloading the UI and making it cluttered as extensions contribute.

But it's something we are constantly evaluating.

Sean

**Comment by leegee** [comment]
That's good to know!  You are all doing a great job!
