### ISSUE TITLE
Command and keybind to toggle on/off state is missing

### ISSUE THREAD

**Issue by mzt** [Microsoft/vscode-spell-check#22]
It's very annoying to see every name etc. colored all the time. We need a way to opt in and out from the feature on the fly.

**Comment by seanmcbreen** [comment]
Some suggestions have been to add support for an ignore files list #27 and the checker supports a dictionary of words to ignore.  Would the combination of these two elements suffice?

**Comment by asifm** [comment]
For me, a toggle command would be very helpful. I write in two modes: the _creating_ mode and the _editing_ mode. When I'm writing my initial drafts, I'm in the creating mode and I don't want to pay any attention to grammar, spelling, punctuation etc. Those things become important only when I'm writing my final drafts, as then I enter the editing mode. I want to stress that this workflow is fairly common among writers — so an ability to easily turn on and off the spell-check will be helpful for many.

**Comment by seanmcbreen** [comment]
Hi I just added a toggle action to the status bar

![image](https://cloud.githubusercontent.com/assets/1051190/17453255/a42d2d90-5b2d-11e6-8255-ed749edd2d14.png)

Try it out and if you like it rate the extension in the marketplace :)

There is currently a bug in VS Code that prevents me from hiding this status bar item for files you don;t want to check.  But once that is resolved I'll try and clean that up as well.

Closing this on for now ;)
