### ISSUE TITLE
Ignore / learn

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-spell-check#23]
Sometimes the tool gets it wrong and I want to ignore what the tool is telling me. Would be great to have an ignore option.

**Comment by DaleKoetke** [comment]
There is an ignore option, but it doesn't work for me. When a misspelled work is selected, type "Alt+." and you have the option to ignore a word.  Selecting this, however, has not effect for me. The word still shows as misspelled.

**Comment by seanmcbreen** [comment]
That's right you can add to the dictionary either manually (in the `spell.json` settings file) or via the `Alt+.` command @DaleKoetke mentions.  

There is a limitation here however - in that to effectively check the document I do some pre-processing of the text file.  That pre-processing removes things like hyphens.  So any I can only reliably ignore words that don't include punctuation in them.

Dale I think that sis likely the issue you are running into.  I'd love to work around the issue but have found no valuable solution unfortunately.

Sean
