### ISSUE TITLE
Code in md is frequently showing mispelled

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-spell-check#24]
I often write code in my markdown files. I propose we ignore words in `<tags>` and inside back ticks `

**Comment by BramGruneir** [comment]
This can be solved add a regex in the `spell.json` file.

I think the default one has this in it already:
```
"/^((`{3}\\\\s*)(\\\\w+)?(\\\\s*([\\\\w\\\\W]+?)\\\\n*)\\\\2)\\\\n*(?:[^\\\\S\\\\w\\\\s]|$)/gm",
```

**Comment by seanmcbreen** [comment]
Yup that's the right approach - you can add an array of regexp's that will be used to avoid chinks of the document for checking.  There are indeed a few in the README you can just grab.

Sean
