### ISSUE TITLE
python not supported?

### ISSUE THREAD

**Issue by martin083** [Microsoft/vscode-spell-check#26]
I added python to the languageIDs:

    "languageIDs": [
        "markdown",
        "latex",
        "plaintext",
        "python"
    ],

not sure if I'm doing anything wrong.  I placed the spell.json file in .vscode.

**Comment by seanmcbreen** [comment]
Hi,

I was just looking at this - what you probably need to do is press `F1` to open the command palette and then type `reload window`.  That will force the spell checker to reload the settings file.

At that point it should work.

It should be noted that checking in a language file can get a little rough as some of the code will be picked up.

Hope that helps - if it does not fell free ot reopen this issue.
Sean
