### ISSUE TITLE
Is it possible to check spell just in the comments part of files 

### ISSUE THREAD

**Issue by lj8385174** [Microsoft/vscode-spell-check#28]
Check spell just in the comments part of .py , .c etc. is very useful. Is it possible to achieve this ?

**Comment by nvanbenschoten** [comment]
The way I was able to achieve this was creating a [`.vscode/spell.json`](https://github.com/Microsoft/vscode-spell-check/blob/master/.vscode/spell.json) file, adding the languageId I'm working in to the `languageIDs` array, and adding the regex `"/^\\\\s*[^\\\\/]{2}.*$/gm"` to the `ignoreRegExp` array. You might need to change the comment character for certain languages like Python, which would mean replacing the `[^\\\\/]` part with `[^#]`. It also will only work with full-line comments.

This seems like an extremely common use case of this extension, so I hope that future development will focus on making this as seamless as possible. This is extremely easy in [Sublime Text](https://www.sublimetext.com/docs/2/spell_checking.html) (and performs a lot better without needing to talk to a web server), so it's a shame that VSCode is lacking in this area.

**Comment by BramGruneir** [comment]
It would be very useful to be able to set specific regexes to certain `languageIDs`. Or else adding a regex that looks for only comments breaks it for all other languages.

**Comment by JVimes** [comment]
Users really need a spell checker for comments+strings in most programming languages, no config required, offline. Not sure if that's in the scope of this extension, but it's a big hole in the ecosystem.

**Comment by seanmcbreen** [comment]
This is not really what I was focused on (but I love the idea) I see a new extension out there that could help:
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

Closing this for now - not because I disagree but I'd love to see others innovate here.
