### ISSUE TITLE
Merging lines?

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode-spell-check#31]
1. Enter the following text in an .md file.
1. Put your cursor/caret on the line `## Set Up`
1. F1 > Spelling suggestions

```
# thin-monitor2

## Set Up

	npm install -g gulp-cli
	npm install -g karma-cli
    npm install -g protractor
	npm install -g eslint
	npm install # Automatically runs bower install

This will install required Node modules, _and_ Bower dependencies. Remember that Bower will try to retrieve external components (outside our company) like angular. You may need to specify proxy in the `.bowerrc` file
```

![image](https://cloud.githubusercontent.com/assets/512816/15314482/0ac79bfc-1c0a-11e6-9a9f-8615de39d8ae.png)

**Comment by seanmcbreen** [comment]
That's not good or expected - I just tried this however and could not get a repro :( sorry.

![image](https://cloud.githubusercontent.com/assets/1051190/15314866/425b3ba0-1bc9-11e6-9331-14bd5c32f1be.png)

This could be a strange issue with the buffer.  It's a hack but pressing `F1` and `reload window` could clear this.

Sean

**Comment by leegee** [comment]
In case it helps...

[image: Inline images 1]

Did you try the text with Windows and/or Unix line-endings...? Just a
thought...

**Comment by seanmcbreen** [comment]
I've done a pretty big overhall of the core engine and with any luck this should be fixed.  I was not able to repro this but I have placed in a few more safe guards.  LMK if you have any luck.

**Comment by leegee** [comment]
Thanks! So far, so good!
