### ISSUE TITLE
Spell check does not show latest evaluation sometimes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-spell-check#32]
I'm assuming there is a race condition where occasionally the character before the last one typed is evaluated afterwards. Perhaps a debounce function would fix?

![image](https://cloud.githubusercontent.com/assets/2193314/15630515/f9b0cabc-24f3-11e6-88f0-892a2a3bff01.png)

**Comment by seanmcbreen** [comment]
I added in a debounce - there will inherently always be some lag unfortunately (I could check on idle as well but that seams invasive).

**Comment by neilsustc** [comment]
It is not solved until now.
Why not evaluate one more time if I stop tying for a relatively long time (e.g. 2 seconds)?

![bug](https://cloud.githubusercontent.com/assets/7588612/16707967/cb2127d6-4614-11e6-855a-7427fe3995ae.gif)

**Comment by seanmcbreen** [comment]
Yay :)

**Comment by neilsustc** [comment]
@seanmcbreen 
Eh.. now I think you could add a *keyboard shortcut* to force revaluation.
I think that's a really good solution. :dizzy_face:
