### ISSUE TITLE
Fork the "teacher" module and use HTTPS by default

### ISSUE THREAD

**Issue by voltagex** [Microsoft/vscode-spell-check#33]
As seen in http://samnewman.io/blog/2016/05/30/want-to-spell-check-read-the-fine-print/

The "After The Deadline" service *does* support HTTPS, and it should definitely be used here (as for whether it's sensible to use a web service for something as simple as spell checking is another matter entirely)

It looks like you'd only have to update the URIs in https://github.com/vesln/teacher/blob/master/lib/api.js#L23

It looks like *teacher* itself is abandoned, having last been updated 4 years ago.

**Comment by paulirish** [comment]
I put up [a PR for `teacher`](https://github.com/vesln/teacher/pull/5), though it's unclear if it'll get merged. A quick solution would be to use my PR branch as a dependency:

```json
	"dependencies": {
		"teacher": "paulirish/teacher#patch-1"
	},
```

But ideally, teacher is forked somewhere a bit more appropriate.

cc @snewman

**Comment by voltagex** [comment]
teacher needs a new maintainer

https://twitter.com/vesln/status/737528819251216384

**Comment by voltagex** [comment]
https://github.com/vesln/teacher/pull/5 is now merged - what's required for this plugin to use the updated version?

**Comment by vermorel** [comment]
+1

**Comment by vesln** [comment]
if any of you folks want push & npm access to teacher do let me know

**Comment by Tyriar** [comment]
@seanmcbreen can you bump the teacher version to 0.1.0 for https requests? Can then update some of the info on the readmes about the web service,

**Comment by vesln** [comment]
@Tyriar i already did

**Comment by Tyriar** [comment]
@vesln I mean for this extension :)

**Comment by seanmcbreen** [comment]
Hi

I just published an updated version of the Spell Checker to use the 0.1.0 version of Teacher.  Thanks @vesln for updating the module and thanks @paulirish for the pull request adding in HTTPS support.  A significant improvement.

I'm closing this issue - re-open if that's the wrong call - I will review all of the other comments/the blog post etc.

Sean

**Comment by vesln** [comment]
@Tyriar 😀  sorry misread what u wrote
