### ISSUE TITLE
Problem with preview editors (new feature in vs code v1.3)

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode-spell-check#36]
Steps:
1. Open a .md file (a *preview editor* will be opened by default)
2. Edit the file
3. Spelling checker won't work

![bug](https://cloud.githubusercontent.com/assets/7588612/16708280/9ccd44d6-461f-11e6-8f17-891cb86eff5d.png)

**Comment by seanmcbreen** [comment]
I updated the checker last night and am unable to repro this - could you give it another try?

**Comment by neilsustc** [comment]
Cool, it works pretty well. :)
And another issue is also solved now.
(Just ignore my comment under #32 )
