### ISSUE TITLE
Umlaut in word -> no suggestion

### ISSUE THREAD

**Issue by noerw** [Microsoft/vscode-spell-check#37]
When there are Umlauts (`ä`, `ö`, `ü`) in a word, there is `No fix suggestions.`, implying that i also can't add the word to the ignore list

**Comment by seanmcbreen** [comment]
Ah thats a great issue - I'll look to fix that in an update thanks for reporting it.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
