### ISSUE TITLE
Warn No handler found for the command: 'Spell.suggestFix'

### ISSUE THREAD

**Issue by Zander1372** [Microsoft/vscode-spell-check#5]
Get his everytime I try to use Alt + .
![image](https://cloud.githubusercontent.com/assets/8130847/11351429/a3e33d86-9204-11e5-8815-2a3e06eda234.png)

**Comment by seanmcbreen** [comment]
That's not good sorry about this - I know this was an issue in an earlier version. Could you try an upgrade `F1` then `ext inst` and then `spell` and try uninstall (or update).  I hope that will work.  There are still some suggestion issues but at worse case you should see....

![image](https://cloud.githubusercontent.com/assets/1051190/11356757/bd0d821a-9215-11e5-94c0-b55a8a0ba34c.png)

If not I'll get on it :)

**Comment by seanmcbreen** [comment]
Oh and the current version is `0.3.0`.

**Comment by chrisSowerby** [comment]
I also get this. Only just installed today. 30 mins ago from this post. so I expect i have the latest version.
Also no words get marked as bad at all.

**Comment by seanmcbreen** [comment]
The checker only works for Markdown currently - it's easy to modify for other languages see comments in Issue #4.

@chrisSowerby is it not working in MarkDown for you?

**Comment by seanmcbreen** [comment]
@Zander1372 OK I think I managed to repro your issue - I believe you are also not in a Markdown file and have not yet opened one.  As a result the core extension has not been activated and when you attempt the keybinding you get that error.  

If you navigate to a `.md` file the extension will activate and you will get a better error message even when not in an `.md` file.  However, I still won't have a suggestion as I only check for errors in a Markdown file.

One way to force spell checking in a different file is to change the selected language mode in the bottom right hand corner temporarily to Markdown.  But this will be a pretty poor experience as I will highlight many of the APIs as spelling mistakes :smile:

**Comment by seanmcbreen** [comment]
Ok I put some additional error checking in place to help w/ this issue.  I also added the ability for other file types outside of MarkDown to be checked.

**Comment by MedhatDawoud** [comment]
I've the same issue
