### ISSUE TITLE
spell checking is not enabled for open files on startup

### ISSUE THREAD

**Issue by noerw** [Microsoft/vscode-spell-check#51]
## steps to reproduce:
- open project
- open a `.md` file
- close code
- reopen code

The spellcheck is only available once i close the .md editor and reopen it.

Or is this desired behaviour, because of security concerns? If so, the button "enable spellcheck" in the bottom statusbar should be available.

**Comment by seanmcbreen** [comment]
I will look into this - I have also seen a few reloading issues.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
