### ISSUE TITLE
Unexpected spelling errors

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-spell-check#52]
Version 0.8.6 with todays insiders. Sometimes (not sure what triggers it) one of my ts files fills with spelling errors.

![screen shot 2016-09-21 at 3 50 12 pm](https://cloud.githubusercontent.com/assets/9205389/18731818/62a9550a-8013-11e6-88b3-885fd8016cda.png)

**Comment by seanmcbreen** [comment]
That would be really bad - I unfortunately can't repro - will chat w/ you on Monday and work it out.

**Comment by seanmcbreen** [comment]
I'm unable to repro so closing for now
