### ISSUE TITLE
Is this thing still working?

### ISSUE THREAD

**Issue by codylindley** [Microsoft/vscode-spell-check#56]
I am using VS code Version 1.7.1 (1.7.1).

I install this, and nothing works. 

e.g. https://www.dropbox.com/s/b35b6tk36t6nnp1/Screenshot%202016-11-12%2016.36.54.png?dl=0

Am I missing something here?

**Comment by s-KaiNet** [comment]
It doesn't work for me too.

**Comment by dwonisch** [comment]
Currently English Spell Check seems to be broken, but other languages, for example German, are working.
This is caused by an issue in After The Deadline Service, as stated in issue #54

**Comment by seanmcbreen** [comment]
I just updated #54 and re-published the extension.  Hopefully it should work now.

**Comment by codylindley** [comment]
Still does not work.
