### ISSUE TITLE
Spell Checks the Markdown preview as well

### ISSUE THREAD

**Issue by IainVM** [Microsoft/vscode-spell-check#57]
Since the preview panel for Markdown is seen as plaintext (by removing the markdown check it still tries to check the preview). The plugin tries to spell check the document.md.render and spits out a handfull of stuff to the errors panel.

**Comment by seanmcbreen** [comment]
Apologies I was unable to repro this could I get a little more context e.g. a step-by-step.

**Comment by IainVM** [comment]
I had this issue for multiple days and reboots, but today trying to write a way to reproduce it, it has stopped happening. If it occures again I shall find a way to reproduce it and post here.

**Comment by seanmcbreen** [comment]
Thanks @IainVM that would be really helpful and sorry you bumped into an issue at all.  For now I'll close this but we can re-open if required.
