### ISSUE TITLE
Using local AtD server

### ISSUE THREAD

**Issue by harmishhk** [Microsoft/vscode-spell-check#59]
Not an issue but a suggestion.

Since the AtD service has not been reliable recently, would it make sense to allow users to specify URL to local/private AtD servers?

I have created a pull request #58 as an example of how this could be implemented.

**Comment by harmishhk** [comment]
Additional info:
A simple way to run local AtD server is using [Docker](https://www.docker.com/), e.g. `docker run -it --rm -p 1049:1049 harmish/atd`

**Comment by ldecicco** [comment]
+1 @harmishhk did you manage to run it locally?

**Comment by harmishhk** [comment]
@ldecicco Yes, I'm now mostly using the local AtD server.

If you want to try it out:
1. Checkout `local-atd-server` from my [fork](https://github.com/harmishhk/vscode-spell-check/tree/local-atd-server), and compile it.
2. Start local AtD server with `docker run -it --rm -p 1049:1049 harmish/atd`.
3. Add `"languageURIs"` field to your `spell.json` as I mentioned in the pull request #58 (with IP address of the machine you are running the local AtD server).

You may need to restart vscode after updating the `spell.json`.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
