### ISSUE TITLE
streamlined usability

### ISSUE THREAD

**Issue by simonsheridan** [Microsoft/vscode-spell-check#60]
I would like to be able to install this via the vscode plugin directory (it doesn't appear to be registered?), and then just hit a shortcut key in any file to toggle spell checking.  That's it.  I'm not sure who would want to configure different file types to check or not check and all this other stuff you have in the readme, maybe some would find it useful but most people just want to be able to toggle a spellchecker.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
