### ISSUE TITLE
Add spell check support to git commit message

### ISSUE THREAD

**Issue by robsonpeixoto** [Microsoft/vscode-spell-check#61]
When I'm writing a git commit message the spell check does not work.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
