### ISSUE TITLE
Additional Code Block ignore example for Readme? Possible default. (suggestion)

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode-spell-check#62]
I have long been in search of way to ignore all within a backtick whether it be

`single backtick`
or
```
triple backtick
```
or with
```PowerShell
Write-Host -Foreground-Color red 'Code tag'
```

I recently took the time to get a regex string that works, I hope it is of use to others, or if there is issue with it let me know. But if it can be added to the README, I thought it could help save some time for people who want it, or to the default json config?

`"/((`{1,3})([^`]+?)\\\\2)/gm"`

Thanks!
-Eric

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
