### ISSUE TITLE
[Feature request] add a command to manually call `TriggerDiagnostics` method for current document

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode-spell-check#66]
Nice extension 👍 
It can be better to provide a command to manually trigger spell check when it's needed.
For example, I can do spell check **as I finish writing** my document, and fix those errors together.
I don't care about the errors when **I'm writing**, and it can also prevent some unnecessary checking.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
