### ISSUE TITLE
expose config for server and/or proxy

### ISSUE THREAD

**Issue by btmurrell** [Microsoft/vscode-spell-check#67]
you mention in your warning that the server connection to afterthedeadline.com / www.polishmywriting.com is not reliable.  It would be great to allow a config to point to a different instance (e.g. what if i wanted to install my own afterthedeadline server in my network and point to it).

Also, I work behind a %(@&*%)@ corporate proxy firewall.  I cannot connect to polishmywriting because of the proxy... i'd at least like to be able to config proxy to reach it.

thanks!

**Comment by harmishhk** [comment]
@btmurrell maybe, #58 pull request can help you.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
