### ISSUE TITLE
Move settings from spell.json to User / Workspace settings

### ISSUE THREAD

**Issue by manojdcoder** [Microsoft/vscode-spell-check#68]
It will nice if this extension could read configurations from User / Workspace settings rather than it's own`spell.json` file for each project.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
