### ISSUE TITLE
How would you run spell-check on entire project?

### ISSUE THREAD

**Issue by kuncevic** [Microsoft/vscode-spell-check#69]
Currently the spell-check runs on only for current opened file. 

![image](https://cloud.githubusercontent.com/assets/1283734/24179427/227282fc-0f03-11e7-9b03-f5578dfe8d93.png)

How would you run the spell-check on entire project/folder ?

**Comment by seanmcbreen** [comment]
This issue should move to the cSpell repo...  Context (and those errors are form cSpell).

This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
