### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by steveharoz** [Microsoft/vscode-spell-check#71]
I made a new markdown file. Then I typed the following:

    # Here is a titl
    
    Blah asdkfljhasd asjhdfiluha a
    kasjdfklja
    iouyyurt

There is no red underline anywhere.

![image](https://cloud.githubusercontent.com/assets/2257540/25020106/c266c2b8-2052-11e7-8a5f-674225156c06.png)

(sorry, I don't have a more specific title than "doesn't work")

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
