### ISSUE TITLE
Latex not supported for spellchecking

### ISSUE THREAD

**Issue by chrisber** [Microsoft/vscode-spell-check#8]
```
LanguageID: latex not suported for spell checking
```
The extension vscode-LaTeX seems not to be compatible when it comes to spell checking, is it possible to support "*.tex" files ?

**Comment by seanmcbreen** [comment]
yes it is there is a new config value in the `spell.json` where you can add additional languages.

See this link for an example.
https://github.com/Microsoft/vscode-spell-check/blob/master/.vscode/spell.json#L21

The checker will unfortunately also pick up quite a few keywords so add them to the dictionary.
