### ISSUE TITLE
README should warn that this extension sends all data to a third party service over insecure HTTP

### ISSUE THREAD

**Issue by csnover** [Microsoft/vscode-spell-check#9]
This extension sends the entire content of documents to a third-party service (After The Deadline) over an insecure HTTP connection.

As this is a potentially serious privacy violation (and not something that users would typically expect, since every OS comes with a built-in spell checker these days!) it should be stated very clearly in the README that this is what will happen, and that this extension shouldn’t be installed by users that aren’t OK with all of their documents being transmitted in this manner.

**Comment by gregvanl** [comment]
Very good suggestion.  Added an Alert to the README.

**Comment by csnover** [comment]
Thanks!
